"use client";
import { AnimatePresence,motion } from "framer-motion";
import { X } from "lucide-react";
import { useState } from "react";
type Props={open:boolean;onClose:()=>void};
export default function InquiryDrawer({open,onClose}:Props){
const [loading,setLoading]=useState(false);
const [form,setForm]=useState({name:"",phone:"",email:"",state:"",city:"",project:"Shri Sai Enclave",message:""});
const handleChange=(e:any)=>setForm({...form,[e.target.name]:e.target.value});
async function submitForm(e:any){e.preventDefault();setLoading(true);try{const r=await fetch("/api/inquiry",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Something went wrong.");alert("Thank you! We'll contact you shortly.");onClose();}catch(err:any){alert(err.message||"Unable to submit form.");}finally{setLoading(false);}}
return(<AnimatePresence>{open&&(<><motion.div className="fixed inset-0 bg-black/70 z-[90]" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={onClose}/><motion.div initial={{x:"100%"}} animate={{x:0}} exit={{x:"100%"}} className="fixed top-0 right-0 h-screen w-full md:w-[520px] bg-[#111] z-[100] overflow-y-auto"><div className="p-10"><div className="flex justify-between"><h2 className="text-white text-4xl">Schedule a Visit</h2><button onClick={onClose}><X className="text-white"/></button></div><form onSubmit={submitForm} className="space-y-5 mt-10"><input name="name" value={form.name} onChange={handleChange} placeholder="Full Name" className="w-full border p-3 rounded text-white bg-transparent"/><input name="phone" value={form.phone} onChange={handleChange} placeholder="Phone" className="w-full border p-3 rounded text-white bg-transparent"/><input type="email" name="email" value={form.email} onChange={handleChange} placeholder="Email" className="w-full border p-3 rounded text-white bg-transparent"/><input name="state" value={form.state} onChange={handleChange} placeholder="State" className="w-full border p-3 rounded text-white bg-transparent"/><input name="city" value={form.city} onChange={handleChange} placeholder="City" className="w-full border p-3 rounded text-white bg-transparent"/><textarea name="message" value={form.message} onChange={handleChange} placeholder="Message" className="w-full border p-3 rounded text-white bg-transparent"/><button type="submit" disabled={loading} className="w-full bg-[#C8A96A] rounded-full py-3">{loading?"Submitting...":"Schedule Visit"}</button></form></div></motion.div></>)}</AnimatePresence>)}